"""Regenerate the search catalog after editing SET data (Python standard library only).
Run: python tools/build_catalog.py
This updates catalog.js only; it never rewrites a question, translation or answer.
"""
from pathlib import Path
from collections import Counter
import json
import re

ROOT = Path(__file__).resolve().parents[1]

def read_set(path: Path) -> dict:
    text = path.read_text(encoding='utf-8')
    marker = 'window.SET='
    if marker not in text:
        raise ValueError(f'{path.name}: window.SET is missing')
    data, _ = json.JSONDecoder().raw_decode(text.split(marker, 1)[1].lstrip())
    if not isinstance(data, dict) or not isinstance(data.get('items'), list):
        raise ValueError(f'{path.name}: invalid SET structure')
    return data

def issues(q: dict) -> list[str]:
    out = []
    if '{' not in q['st']:
        out.append('missing underline')
    if len({o['w'].strip().casefold() for o in q['op']}) != len(q['op']):
        out.append('duplicate options')
    if not q['tg']['w'].strip():
        out.append('empty target')
    return out

def build() -> None:
    files = sorted(ROOT.glob('set-[0-9][0-9].html'))
    if not files:
        raise SystemExit('No set-NN.html files were found.')
    catalog = {'version': 2, 'total': 0, 'uniqueWords': 0,
               'sets': [], 'items': []}
    headwords = set()
    seen = set()
    for path in files:
        data = read_set(path)
        number = int(re.search(r'set-(\d+)', path.name).group(1))
        if data['id'] != f's{number:02}':
            raise ValueError(f'{path.name}: SET id does not match its filename')
        questions = data['items']
        if not questions:
            raise ValueError(f'{path.name}: this set has no questions')
        sources = Counter(q['sc'].rstrip(']') for q in questions)
        catalog['sets'].append({'id': data['id'], 'number': number,
            'first': questions[0]['no'], 'last': questions[-1]['no'],
            'count': len(questions), 'sources': [s for s, _ in sources.most_common(3)]})
        for q in questions:
            if q['no'] in seen:
                raise ValueError(f'Duplicate question number: {q["no"]}')
            if not isinstance(q['an'], int) or not 0 <= q['an'] < len(q['op']):
                raise ValueError(f'Invalid answer index in question {q["no"]}')
            seen.add(q['no'])
            if q['tg']['w'].strip():
                headwords.add(q['tg']['w'].strip().casefold())
            item = {'n': q['no'], 's': number, 'w': q['tg']['w'], 'k': q['tg']['ko'],
                    'c': q['sc'].rstrip(']'), 't': q['tp'],
                    'o': len(q['op']), 'a': q['an']}
            if q.get('rev'):
                item['r'] = q['rev']
            problems = issues(q)
            if problems:
                print(f'확인 필요: {q["no"]}번 {", ".join(problems)}')
            catalog['items'].append(item)
    catalog['total'] = len(catalog['items'])
    catalog['uniqueWords'] = len(headwords)
    target = ROOT / 'assets' / 'catalog.js'
    target.write_text('/* Generated by tools/build_catalog.py. Do not hand-edit. */\n'
                      + 'window.VC_CATALOG='
                      + json.dumps(catalog, ensure_ascii=False, separators=(',', ':'))
                      + ';\n', encoding='utf-8')
    print(f'Updated {target.name}: {len(files)} sets, {catalog["total"]:,} questions.')
    if len(files) != 20 or catalog['total'] != 1913:
        print('NOTE: update static homepage descriptions and the import limits in core.js if you change the collection size.')

if __name__ == '__main__':
    try:
        build()
    except (ValueError, KeyError, json.JSONDecodeError, OSError) as exc:
        raise SystemExit(f'Catalog update failed: {exc}')
